### [전체 목차](../../README.md)
### [이전 페이지](../README.md)

# 5 일차
예외처리

## 목차

- [Exception handling](#exception-handling)
- [finally](#finally)

## [Exception handling](#목차)
Exception을 처리해서 정상화 시키는 작업

```python
try:
    Exception 발생가능한 코드 블록
except [Exception클래스 이름 [as 변수]] :
    처리 코드   
```

- **except block**
    - 모든 Exception을 처리하는 경우 `except:` 로 선언한다.
    - 특정 Exception만 따로 처리할 경우 `except Exception 클래스 이름` 을 선언한다.
        
```python
# try - except
print("시작") # 1.

try:
    num = int(input()) # 2.
    result = 10 // num # 3.
    print("결과:", result) # 4.
    
except ValueError: # except Exception 이름 => Exception 이름의 예외만 처리
    print("실행도중 ValueError 발생했습니다.") # 예외처리

except ZeroDivisionError:
    print("실행도중 ZeroDivisionError 발생함.")

except: # 위 두개 Exception을 제외한 나머지 Exception을 처리하는 block
    print("ValueError, ZDE 이외의 예외가 발생함.")

print("프로그램 종료") # 5.
```

- 예외가 발생하지 않은 경우 실행 순서
    - 1 => 2 => 3 => 4 => 5 ('예외처리'는 실행이 안됨)
- 예외가 발생한 경우
    - 2번 라인에서 발생
        - 1 => 2(x) => 예외처리 => 5
        - 실행 안된 라인: 2, 3, 4
    - 3번 라인에서 발생
        - 0을 입력하면 3번에서 에러 발생

## [finally](#목차)

- 예외 발생여부와 관계없이 무조건 실행되는 코드블록
    - try 구문에 **반드시 실행되야 하는 코드블록을 작성할때 사용한다.**
    - 보통 프로그램이 외부자원과 연결해서 데이터를 주고 받는 작업을 할때 마지막 연결을 종료하는 작업을 finally 블록에 넣는다.
- finally 는 except 보다 먼저 올 수 없다.
    - 구문순서
        1. try - except - finally
        1. try - except
        1. try - finally
print("시작")
try:
    print(1)
    print(2)
    print(aaa) # type: ignore
except NameError:
    print(3)
finally:
    print("정상코드-반드시 실행되야함.")

print("종료")
# run.py 파일과 연결해서 그 안의 text를 읽기.

try:
    # 1. 파일과 연결 => 사용
    fr = open("run.py", encoding="UTF-8")
    # 2. 읽기
    txt = fr.read()
    print(txt) # 사용
except:
    print("처리")
finally:
    # 3. 연결 끊기(닫기) => 사용종료
    fr.close()


### [목차로 돌아가기](#목차)
## [이전 페이지](../README.md)
